[package]
name = "datatools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
aws-config = "0.55.1"
aws-types = "0.55.1"
deltalake = { version = "0.11", features = ["datafusion", "s3"]}
datafusion = { version = "24" }
object_store = { version = "0.5.6", features=["aws_profile"] }
chrono = "0.4.24"
axum = "0.6.18"
hyper = { version = "0.14.26", features = ["full"] }
tower = "0.4.13"
tokio = { version = "1", features = ["full"] }
url = { version = "2.3" }
