[package]
name = "datatools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
anyhow = { version = "1.0" }
deltalake = { version = "0.16", features = ["datafusion", "s3"]}
datafusion = { version = "31" }
object_store = { version = "0.7.0", features=["aws"] }
chrono = "0.4.24"
axum = "0.6.18"
hyper = { version = "0.14.26", features = ["full"] }
tower = "0.4.13"
tokio = { version = "1", features = ["full"] }
url = { version = "2.3" }
futures = "0.3"
log = "0.4.19"
